//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymMember
    {
        public string MemberCode { get; set; }
        public string MemberName { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<System.DateTime> MemberShipStartDate { get; set; }
        public string MemberShipDuration { get; set; }
    }
}
